# -*- coding: utf-8 -*-
"""Assignment day 2_py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1prL50KQAlQRTB9w5Ug2uu3FBeeIBIsni

**1.LISTS**
"""

a=[1,5,7.5,'me','i',]
len(a)

a.append('ll')
a

a.remove('me')
a

a.index('ll')

a.pop()
a

"""**2.Tuples**"""

c=('me',7,8.5)
c.index(7)

len(c)

d=list(c)
d

type(c)

e=tuple(d)
f=c+e
del(e)
e

"""#3.Dictionaries"""

a={"name":"me","num":2,"floa":2.5}
a.keys()

a.values()

a.copy()

a.pop("num")
a

a.update({"num":2})
a

"""#4.Set"""

a={"Fiat","Benz","BMW"}
b={"Toyota","Sumo","Jaguar"}
c=a.union(b)
c

c.discard('Benz')
c

d=a.intersection(b)
d

d=b.issubset(c)
d

b.pop()
b

"""#5.Strings"""

a="Nithai"
len(a)

a.upper()
a.lower()

a.replace("i","y")

my=70
i="my percentage is {}"
i.format(my)

b="Hello World"
b.split()