# -*- coding: utf-8 -*-
"""Assignmentday3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y7cIOpNyVX4A0k1ut71-vnnQJRzVhGhk

1.Flight land
"""

l=1000
a=int(input())
if a<=l:
  print("land the plane")
if a>l and a<5000:
  print("come down to 1000ft")  
elif a>5000:
  print("go around and try later")

"""2.Prime"""

n=200
for num in range(1,n+1):
  if num>1:
    for i in range(2,num):
      if num%i==0:
        break
    else:
      print(num)